from collections.abc import AsyncIterator
from typing import Any

from langchain_core.messages import HumanMessage

from app.domain.agents.entities import Message
from app.domain.agents.ports import AgentRunner
from app.infrastructure.agents.extract_ai_message_token import extract_ai_message_token


class LangGraphAgentRunner(AgentRunner):
    """AgentRunner adapter backed by a compiled LangGraph graph (see `build_chat_graph`).

    Streams LLM tokens as they're generated by running `graph.astream(...,
    stream_mode="messages")`. With `stream_mode="messages"`, LangGraph yields
    `(message_chunk, metadata)` tuples for every chat-model token; `metadata` is
    unused here but kept in the unpack for clarity about the tuple shape.
    """

    def __init__(self, graph: Any) -> None:
        self._graph = graph

    async def stream(self, thread_id: str, message: Message) -> AsyncIterator[str]:
        config = {"configurable": {"thread_id": thread_id}}
        input_state = {"messages": [HumanMessage(content=message.content)]}

        async for message_chunk, _metadata in self._graph.astream(
            input_state, config=config, stream_mode="messages"
        ):
            token = extract_ai_message_token(message_chunk)
            if token:
                yield token
