from dataclasses import dataclass, field
from datetime import UTC, datetime


@dataclass(slots=True)
class TelegramLinkToken:
    """A short-lived, single-use token generated by `POST /api/v1/telegram/link-token`,
    tied to the requesting user, and consumed by the Telegram webhook's `/start <token>`
    handler to complete the linking flow.

    `consumed_at` is `None` until the token is used; `TelegramLinkTokenRepository.consume`
    atomically checks `consumed_at is None and expires_at > now()` and stamps `consumed_at`
    in one DB round trip, so a token can never be replayed (e.g. the same deep link opened
    twice, or a race between two webhook deliveries for the same update).
    """

    token: str
    user_id: str
    expires_at: datetime
    consumed_at: datetime | None = None
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
