"""telegram_links, telegram_link_tokens

Track-5 T1 data layer: per-user Telegram account linking (issue #14 — "Telegram per-user
linking and Watchdog alert delivery"). Two tables:

- `telegram_links` — the verified `user_id` <-> `telegram_chat_id` mapping, resolved by
  `TelegramNotificationChannel` (`infrastructure/notification/telegram_notification_channel.py`)
  to route a Watchdog `Alert` (issue #10) to the right chat.
- `telegram_link_tokens` — short-lived, single-use tokens behind the `/start <token>`
  deep-link flow (`POST /api/v1/telegram/link-token` generates them, the Telegram webhook
  handler consumes them).

Both tables are written by this backend using the Supabase service-role key (bypasses
RLS) — the same visibility model as `signals`/`briefings` in migration 0001: the RLS
policies here are defense-in-depth (mirroring the `watchlists` owner-only pattern), not
the primary write path. No `update` policy on either table: `telegram_links` uses
unlink-then-relink (see `TelegramLink`'s docstring) instead of update-in-place, and
`telegram_link_tokens` is only ever mutated by the backend's `consume()` (a conditional
UPDATE via the service-role key), never directly by a client.

Compliance note (same stance as migration 0001): neither table stores anything
buy/sell/order/quantity/price_target-shaped — this is account-linking plumbing, not a
trading surface.

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-11

"""

from collections.abc import Sequence

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_UPGRADE_SQL = """
-- =============================================================================
-- telegram_links — one verified user_id <-> telegram_chat_id mapping per user.
-- Unique on both columns: a user has at most one linked chat, and a chat links to at
-- most one user. Relinking (a new /start <token> for a user, or a chat starting a new
-- user's link flow) goes through the repository's unlink-then-relink delete+insert, so
-- no `update` policy is needed here.
-- =============================================================================
create table if not exists public.telegram_links (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users (id) on delete cascade,
    telegram_chat_id text not null,
    linked_at timestamptz not null default now(),
    unique (user_id),
    unique (telegram_chat_id)
);

create index if not exists telegram_links_user_id_idx on public.telegram_links (user_id);

alter table public.telegram_links enable row level security;

create policy "telegram_links_select_own" on public.telegram_links
    for select using (auth.uid() = user_id);

create policy "telegram_links_insert_own" on public.telegram_links
    for insert with check (auth.uid() = user_id);

create policy "telegram_links_delete_own" on public.telegram_links
    for delete using (auth.uid() = user_id);

-- =============================================================================
-- telegram_link_tokens — short-lived, single-use tokens behind the /start <token>
-- deep-link flow. `token` is the primary key (an unguessable `secrets.token_urlsafe`
-- value, generated by POST /api/v1/telegram/link-token) rather than a surrogate uuid,
-- since it's looked up directly by its own value, never joined on.
-- =============================================================================
create table if not exists public.telegram_link_tokens (
    token text primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    expires_at timestamptz not null,
    consumed_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists telegram_link_tokens_user_id_idx
    on public.telegram_link_tokens (user_id);

alter table public.telegram_link_tokens enable row level security;

create policy "telegram_link_tokens_select_own" on public.telegram_link_tokens
    for select using (auth.uid() = user_id);

create policy "telegram_link_tokens_insert_own" on public.telegram_link_tokens
    for insert with check (auth.uid() = user_id);

create policy "telegram_link_tokens_delete_own" on public.telegram_link_tokens
    for delete using (auth.uid() = user_id);
"""

_DOWNGRADE_SQL = """
drop table if exists public.telegram_link_tokens cascade;
drop table if exists public.telegram_links cascade;
"""


def upgrade() -> None:
    op.execute(_UPGRADE_SQL)


def downgrade() -> None:
    op.execute(_DOWNGRADE_SQL)
